import type { AppData } from "@/components/app-card";

export const SEED_APPS: AppData[] = [
  {
    id: "1",
    slug: "dm-compass",
    name: "DM Compass",
    tagline: "糖尿病病棟管理の計算・ガイドツール",
    description:
      "研修医・病棟担当医のための糖尿病マネジメント支援アプリ。必要エネルギー量計算、糖尿病性腎症病期分類、末梢輸液インスリン混注量、IVHインスリン混注量、スライディングスケール自動生成などの計算ツールと、インスリン製剤一覧、経口血糖降下薬、糖尿病分類、合併症リファレンスなどのガイド機能を搭載。スマートフォンに最適化されたUIで、病棟での即時参照が可能です。",
    price: 0,
    category: ["diabetes-endocrine", "resident"],
    app_url: "https://iwatatsu2.github.io/dm-compass/",
    demo_url: "https://iwatatsu2.github.io/dm-compass/",
    thumbnail_url: "/thumbnails/thumbnail-dm-compass.png",
    screenshots: ["/screenshots/dm-compass-1.png"],
    target_roles: ["doctors", "nurses"],
    developer_name: "岩本 達也",
    developer_specialty: "糖尿病内分泌代謝内科",
    access_count: 1243,
  },
  {
    id: "2",
    slug: "insucalc",
    name: "InsuCalc",
    tagline: "1型糖尿病のボーラスインスリン計算",
    description:
      "1型糖尿病患者のためのボーラスインスリン計算アプリ。カーボカウントに基づく食事ボーラスと補正ボーラスを簡単に計算できます。",
    price: 0,
    category: ["diabetes-endocrine"],
    app_url: "https://insulin-calculator.vercel.app/",
    demo_url: "https://insulin-calculator.vercel.app/",
    thumbnail_url: null,
    screenshots: [],
    target_roles: ["general"],
    developer_name: "岩本 達也",
    developer_specialty: "糖尿病内分泌代謝内科",
    access_count: 876,
  },
  {
    id: "3",
    slug: "t1life",
    name: "T1Life",
    tagline: "1型糖尿病コミュニティ＆ライフサポート",
    description:
      "1型糖尿病患者のためのコミュニティアプリ。日常生活の記録、情報共有、サポート機能を提供します。",
    price: 0,
    category: ["diabetes-endocrine"],
    app_url: "https://t1life.vercel.app/",
    demo_url: "https://t1life.vercel.app/",
    thumbnail_url: null,
    screenshots: [],
    target_roles: ["general"],
    developer_name: "岩本 達也",
    developer_specialty: "糖尿病内分泌代謝内科",
    access_count: 654,
  },
  {
    id: "4",
    slug: "endo-compass",
    name: "Endo Compass",
    tagline: "内分泌負荷試験リファレンス",
    description:
      "内分泌疾患の負荷試験プロトコル、判定基準、鑑別診断をまとめたリファレンスアプリ。",
    price: 0,
    category: ["diabetes-endocrine", "resident"],
    app_url: "#",
    demo_url: null,
    thumbnail_url: "/thumbnails/thumbnail-endo-compass.png",
    screenshots: [],
    target_roles: ["doctors"],
    developer_name: "岩本 達也",
    developer_specialty: "糖尿病内分泌代謝内科",
    access_count: 412,
  },
  {
    id: "5",
    slug: "electrolyte-compass",
    name: "Electrolyte Compass",
    tagline: "電解質異常の鑑別・計算ツール",
    description:
      "電解質異常の鑑別診断、補正計算、緊急対応をサポートするリファレンスアプリ。",
    price: 0,
    category: ["resident", "emergency"],
    app_url: "#",
    demo_url: null,
    thumbnail_url: "/thumbnails/thumbnail-electrolyte-compass.png",
    screenshots: [],
    target_roles: ["doctors"],
    developer_name: "岩本 達也",
    developer_specialty: "糖尿病内分泌代謝内科",
    access_count: 328,
  },
];
