import type { AppData } from "@/components/app-card";

export const SEED_APPS: AppData[] = [
  {
    id: "18",
    slug: "ketto-quest",
    name: "血糖値クエスト",
    tagline: "遊んで学べる血糖ゲーム｜コンビニ・外食の選び方をRPGで",
    description:
      "糖尿病専門医が作った、遊びながら食事の選び方が身につくRPG風の学習ゲーム。コンビニ・牛丼・ラーメン・居酒屋・回転寿司など日常の場面で「どれを選ぶ？」に答え、章を進めてボスと戦い、主人公ドクターいわたつを育てていきます。1日の食事を選んで血糖の波形（Time in Range）を管理する『血糖カーブ・サバイバル』、自分が食べたものを入れて血糖の動きの目安を見る『マイ食事チェッカー』も搭載。楽しみながら“なんとなくこっちかな”という感覚を養うことを目的にしています。スマホのブラウザで完全無料、インストール不要。※本アプリは学習・啓発用で医療機器ではありません。表示される内容は一般的な情報であり、効果には個人差があります。実際の食事や治療の判断は主治医にご相談ください。",
    price: 0,
    category: ["diabetes-endocrine"],
    app_url: "https://ketto-quest.vercel.app/",
    demo_url: "https://ketto-quest.vercel.app/",
    thumbnail_url: "/thumbnails/thumbnail-ketto-quest.png",
    screenshots: [],
    target_roles: ["general"],
    developer_name: "岩本 達也",
    developer_specialty: "糖尿病内分泌代謝内科",
    access_count: 0,
  },
  {
    id: "17",
    slug: "gluview",
    name: "GluView",
    tagline: "リブレ2・Dexcom G7 対応｜血糖をリビングの大画面モニターに",
    description:
      "【FreeStyle リブレ2 と Dexcom G7 の両方に対応】リブレ2（LibreLinkUp連携）または Dexcom G7（シェア連携）の血糖値を、使っていないタブレットやスマホに大きく表示する見守りディスプレイ。数字・トレンド矢印・直近3時間グラフ・TIRをひと目で確認でき、低血糖・高血糖は音と画面で警告します（音の種類・音量・画面演出をカスタマイズ可）。1型糖尿病のお子さんを持つご家族や介護者が、リビングに常設して離れていても血糖を見守れます。iPhone・Android・タブレット対応、完全無料。各家庭が自分のリブレ／Dexcomの認証情報を端末内にのみ保存する方式で、サーバーには保存しません。※本アプリは医療機器ではありません。低血糖等の警告は必ずLibreLink／Dexcom等の公式アプリと併用してください。",
    price: 0,
    category: ["diabetes-endocrine"],
    app_url: "https://glucose-display.vercel.app/",
    demo_url: "https://glucose-display.vercel.app/?demo=1",
    thumbnail_url: "/thumbnails/thumbnail-gluview.png",
    screenshots: [],
    target_roles: ["general"],
    developer_name: "岩本 達也",
    developer_specialty: "糖尿病内分泌代謝内科",
    access_count: 0,
  },
  {
    id: "16",
    slug: "pharma-dm-guide",
    name: "PharmaDM Guide",
    tagline: "病棟で迷ったら、ここで確認。糖尿病薬の判断フローチャート",
    description:
      "薬剤師のための糖尿病薬 判断支援ツール。術前休薬ガイド、シックデイ対応、食止め時の対応、周術期の血糖管理、腎機能別用量調整、注射製剤の取り扱い、薬物相互作用、高齢者の薬剤選択など12のフローチャートを搭載。ステップバイステップの質問に答えるだけで、エビデンスに基づいた推奨アクション・根拠・注意点を表示します。スマートフォンに最適化されたUIで、病棟での即時参照が可能です。",
    price: 0,
    category: ["diabetes-endocrine"],
    app_url: "https://pharma-dm-guide.vercel.app/",
    demo_url: "https://pharma-dm-guide.vercel.app/",
    thumbnail_url: "/thumbnails/thumbnail-pharma-dm-guide.png",
    screenshots: [],
    target_roles: ["pharmacists"],
    developer_name: "岩本 達也",
    developer_specialty: "糖尿病内分泌代謝内科",
    access_count: 0,
  },
  {
    id: "1",
    slug: "dm-compass",
    name: "DM Compass",
    tagline: "糖尿病病棟管理の計算・ガイドツール",
    description:
      "研修医・病棟担当医のための糖尿病マネジメント支援アプリ。必要エネルギー量計算、糖尿病性腎症病期分類、末梢輸液インスリン混注量、IVHインスリン混注量、スライディングスケール自動生成などの計算ツールと、インスリン製剤一覧、経口血糖降下薬、糖尿病分類、合併症リファレンスなどのガイド機能を搭載。スマートフォンに最適化されたUIで、病棟での即時参照が可能です。",
    price: 0,
    category: ["diabetes-endocrine", "resident"],
    app_url: "https://dm-compass.vercel.app/",
    demo_url: "https://dm-compass.vercel.app/",
    thumbnail_url: "/thumbnails/thumbnail-dm-compass.png",
    screenshots: ["/screenshots/dm-compass-1.png"],
    target_roles: ["doctors", "nurses"],
    developer_name: "岩本 達也",
    developer_specialty: "糖尿病内分泌代謝内科",
    access_count: 0,
  },
  {
    id: "2",
    slug: "insucalc",
    name: "InsuCalc",
    tagline: "1型糖尿病のボーラスインスリン計算",
    description:
      "1型糖尿病患者のためのボーラスインスリン計算アプリ。カーボカウントに基づく食事ボーラスと補正ボーラスを簡単に計算できます。",
    price: 0,
    category: ["diabetes-endocrine"],
    app_url: "https://insulin-calculator.vercel.app/",
    demo_url: "https://insulin-calculator.vercel.app/",
    thumbnail_url: null,
    screenshots: [],
    target_roles: ["general"],
    developer_name: "岩本 達也",
    developer_specialty: "糖尿病内分泌代謝内科",
    access_count: 0,
  },
  {
    id: "3",
    slug: "t1life",
    name: "T1Life",
    tagline: "1型糖尿病コミュニティ＆ライフサポート",
    description:
      "1型糖尿病患者のためのコミュニティアプリ。日常生活の記録、情報共有、サポート機能を提供します。",
    price: 0,
    category: ["diabetes-endocrine"],
    app_url: "https://t1life.vercel.app/",
    demo_url: "https://t1life.vercel.app/",
    thumbnail_url: null,
    screenshots: [],
    target_roles: ["general"],
    developer_name: "岩本 達也",
    developer_specialty: "糖尿病内分泌代謝内科",
    access_count: 0,
  },
  {
    id: "4",
    slug: "endo-compass",
    name: "Endo Compass",
    tagline: "内分泌負荷試験リファレンス",
    description:
      "内分泌疾患の負荷試験プロトコル、判定基準、鑑別診断をまとめたリファレンスアプリ。",
    price: 0,
    category: ["diabetes-endocrine", "resident"],
    app_url: "#",
    demo_url: null,
    thumbnail_url: "/thumbnails/thumbnail-endo-compass.png",
    screenshots: [],
    target_roles: ["doctors"],
    developer_name: "岩本 達也",
    developer_specialty: "糖尿病内分泌代謝内科",
    access_count: 0,
  },
  {
    id: "5",
    slug: "glucose-diary",
    name: "Glucose Diary",
    tagline: "毎日の血糖記録を、かしこく管理する血糖自己管理アプリ",
    description:
      "糖尿病患者のための血糖自己管理アプリ。1日7ポイントの血糖値記録に加え、体重・血圧・食事・歩数などの生活データをまとめて記録できます。週間トレンドグラフで血糖パターンを可視化し、低血糖・高血糖のパターンを自動検出してインスリン調整のアドバイスを提示。インスリン・GLP-1・GIP/GLP-1製剤のデータベースを内蔵し、週1回注射の次回投与日管理にも対応。受診時には期間レポートを自動生成し、主治医への共有もスムーズです。PWA対応でスマートフォンにホーム画面追加して使えます。",
    price: 0,
    category: ["diabetes-endocrine"],
    app_url: "https://glucose-diary-iwatatsu2.vercel.app/",
    demo_url: "https://glucose-diary-iwatatsu2.vercel.app/",
    thumbnail_url: "/thumbnails/thumbnail-glucose-diary.png",
    screenshots: [],
    target_roles: ["general"],
    developer_name: "岩本 達也",
    developer_specialty: "糖尿病内分泌代謝内科",
    access_count: 0,
  },
  {
    id: "6",
    slug: "electrolyte-compass",

    name: "Electrolyte Compass",
    tagline: "電解質異常の鑑別・計算ツール",
    description:
      "電解質異常の鑑別診断、補正計算、緊急対応をサポートするリファレンスアプリ。",
    price: 0,
    category: ["resident", "emergency"],
    app_url: "#",
    demo_url: null,
    thumbnail_url: "/thumbnails/thumbnail-electrolyte-compass.png",
    screenshots: [],
    target_roles: ["doctors"],
    developer_name: "岩本 達也",
    developer_specialty: "糖尿病内分泌代謝内科",
    access_count: 0,
  },
  {
    id: "7",
    slug: "obesity-checker",
    name: "肥満症チェッカー",
    tagline: "肥満症の治療適応を3ステップでかんたん判定",
    description:
      "肥満症の治療適応をBMI計算→健康障害チェック→判定の3ステップで簡単に確認できるWebアプリ。肥満症診療ガイドライン2022に準拠し、BMI 35以上の高度肥満症、BMI 25以上+健康障害ありの肥満症を自動判定。GLP-1受容体作動薬の適応チェックにも対応。個人情報の入力不要で、患者さんへのセルフチェックツールとしても活用できます。",
    price: 0,
    category: ["diabetes-endocrine"],
    app_url: "https://obesity-checker-tau.vercel.app/",
    demo_url: "https://obesity-checker-tau.vercel.app/",
    thumbnail_url: "/thumbnails/thumbnail-obesity-checker.png",
    screenshots: [],
    target_roles: ["doctors", "general"],
    developer_name: "岩本 達也",
    developer_specialty: "糖尿病内分泌代謝内科",
    access_count: 0,
  },
  {
    id: "8",
    slug: "weekly-shot",
    name: "WeeklyShot",
    tagline: "週1回のGLP-1注射、もう打ち忘れない",
    description:
      "GLP-1受容体作動薬の週1回注射スケジュールをLINEでリマインドする無料ツール。マンジャロ、オゼンピック、トルリシティなどの週1回製剤に対応。注射予定日にLINEで自動通知し、「済」と返信するだけで記録完了。登録30秒・アプリインストール不要で、患者さんのアドヒアランス向上をサポートします。糖尿病・肥満症専門医が設計・運営。",
    price: 0,
    category: ["diabetes-endocrine"],
    app_url: "https://weekly-shot.vercel.app/",
    demo_url: "https://weekly-shot.vercel.app/",
    thumbnail_url: "/thumbnails/thumbnail-weekly-shot.png",
    screenshots: [],
    target_roles: ["general"],
    developer_name: "岩本 達也",
    developer_specialty: "糖尿病内分泌代謝内科",
    access_count: 0,
  },
  {
    id: "9",
    slug: "kidney-rx",
    name: "KidneyRx",
    tagline: "腎機能に応じた薬剤用量をすばやく検索",
    description:
      "腎機能に応じた薬剤の用法用量をすばやく検索できるリファレンスアプリ。372件以上の医薬品を収録し、CKD保存期・透析患者への投与量調節を一目で確認できます。常用量・注意・減量・禁忌の4段階で用量区分を明示。内服薬・注射薬・外用薬に対応し、腎機能低下患者への適切な薬物療法をサポートします。",
    price: 0,
    category: ["resident", "nephrology"],
    app_url: "https://renal-dose-checker.vercel.app/",
    demo_url: "https://renal-dose-checker.vercel.app/",
    thumbnail_url: "/thumbnails/thumbnail-kidney-rx.png",
    screenshots: [],
    target_roles: ["doctors", "pharmacists"],
    developer_name: "岩本 達也",
    developer_specialty: "糖尿病内分泌代謝内科",
    access_count: 0,
  },
  {
    id: "10",
    slug: "infecti-ref",
    name: "InfectiRef",
    tagline: "感染症・抗菌薬リファレンス",
    description:
      "感染症の治療方針と抗菌薬の用量・用法をまとめた臨床リファレンスアプリ。市中肺炎をはじめとする主要感染症について、IDSA/ATS 2019やJAID/JSC 2019など国内外のガイドラインに基づいた推奨治療法を提示。初期治療から段階的エスカレーション、de-escalationまでの治療ステップを一覧でき、抗菌薬データベースも搭載。臨床現場での迅速な判断をサポートします。",
    price: 0,
    category: ["resident", "infectious-disease"],
    app_url: "https://infecti-ref.vercel.app/",
    demo_url: "https://infecti-ref.vercel.app/",
    thumbnail_url: "/thumbnails/thumbnail-infecti-ref.png",
    screenshots: [],
    target_roles: ["doctors", "pharmacists"],
    developer_name: "岩本 達也",
    developer_specialty: "糖尿病内分泌代謝内科",
    access_count: 0,
  },
  {
    id: "11",
    slug: "nurse-shift",
    name: "Nurse Shift",
    tagline: "みんなの休み、ひと目でわかる。",
    description:
      "看護師のためのシフト管理アプリ。ワンタップでシフト入力、パターン一括設定、グループ共有で同僚の休みがひと目でわかります。共通休みハイライト、天気予報連動、メモ機能も搭載。PWA対応でスマホのホーム画面に追加して使えます。",
    price: 0,
    category: ["other"],
    app_url: "https://nurse-shift-azure.vercel.app/",
    demo_url: "https://nurse-shift-azure.vercel.app/",
    thumbnail_url: null,
    screenshots: [],
    target_roles: ["nurses"],
    developer_name: "岩本 達也",
    developer_specialty: "糖尿病内分泌代謝内科",
    access_count: 0,
  },
  {
    id: "12",
    slug: "hiragana-battle",
    name: "ひらがなバトル",
    tagline: "親子で楽しくひらがな学習",
    description:
      "お子さまのひらがな学習をゲーム感覚でサポートするアプリ。ひらがなを読んで正しい選択肢をタップするバトル形式で、楽しみながら自然とひらがなが身につきます。",
    price: 0,
    category: ["other"],
    app_url: "https://hiragana-battle.vercel.app/",
    demo_url: "https://hiragana-battle.vercel.app/",
    thumbnail_url: null,
    screenshots: [],
    target_roles: ["general"],
    is_tool: true,
    developer_name: "岩本 達也",
    developer_specialty: "糖尿病内分泌代謝内科",
    access_count: 0,
  },
  {
    id: "13",
    slug: "hissan-master",
    name: "ひっさんマスター",
    tagline: "筆算をゲームで楽しくマスター",
    description:
      "足し算・引き算・掛け算の筆算をゲーム形式で練習できる学習アプリ。難易度別のステージをクリアしながら、計算力を楽しく鍛えられます。",
    price: 0,
    category: ["other"],
    app_url: "https://hissan-master.vercel.app/",
    demo_url: "https://hissan-master.vercel.app/",
    thumbnail_url: null,
    screenshots: [],
    target_roles: ["general"],
    is_tool: true,
    developer_name: "岩本 達也",
    developer_specialty: "糖尿病内分泌代謝内科",
    access_count: 0,
  },
  {
    id: "14",
    slug: "morning-checker",
    name: "あさのしたく チェッカー",
    tagline: "こどもの朝・夜の準備をイラストでチェック",
    description:
      "4歳〜小学生向け。かわいいイラストをタッチして、朝や夜の準備を楽しく習慣化。1〜4人対応、朝/夜モード切替、自由タスク追加OK。月〜金の5日間連続達成でごほうび演出つき。タブレット横画面での利用がおすすめです。",
    price: 0,
    category: ["other"],
    app_url: "https://morning-checker.vercel.app/",
    demo_url: "https://morning-checker.vercel.app/",
    thumbnail_url: null,
    screenshots: [],
    target_roles: ["general"],
    is_tool: true,
    developer_name: "岩本 達也",
    developer_specialty: "糖尿病内分泌代謝内科",
    access_count: 0,
  },
  {
    id: "15",
    slug: "hiragana-master",
    name: "ひらがなマスター",
    tagline: "楽しく遊んでひらがなを覚えよう",
    description:
      "ひらがなの読み書きを楽しく学べる子ども向け学習アプリ。ゲーム感覚で繰り返し練習でき、自然とひらがなが身につきます。",
    price: 0,
    category: ["other"],
    app_url: "https://hiragana-app-ten.vercel.app/",
    demo_url: "https://hiragana-app-ten.vercel.app/",
    thumbnail_url: null,
    screenshots: [],
    target_roles: ["general"],
    is_tool: true,
    developer_name: "岩本 達也",
    developer_specialty: "糖尿病内分泌代謝内科",
    access_count: 0,
  },
];
